import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      username: "corekteam",
      email: "corekteam12@gmail.com",
      password: bcrypt.hashSync("corek12"),
      admin: true,
      verified: true
    }
  ],
  courses: [
    {
      name: "AI and Machine Learning",
      slug: "AI and Machine Learning",
      author: "Keny White",
      category: "Forex",
      price: 20,
      image: "/images/course2.jpg",
      image2: "/images/course2Big.jpg",
      rating: 1,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      duration: "25 hours",
      skill_level: "Beginner",
      language: "English",
      instructorImg1: "/images/instructor.jpeg",
      instructorImg2: "/images/instructor2.jpeg",
      aka: "Professor",
      instructorInfo: "Lorem ipsum dolor sit amet. Qui incidunt dolores non similique ducimus et debitis molestiae. Et autem quia eum reprehenderit voluptates est reprehenderit illo est enim perferendis est neque sunt. Nam amet sunt aut vero mollitia ut ipsum corporis vel facere eius et quia aspernatur qui fugiat repudiandae. Et officiis inventore et quis enim ut quaerat corporis sed reprehenderit odit sit saepe distinctio et accusantium repellendus ea enim harum."
    },
    {
      name: "Introduction to Cybersecurity for Business",
      slug: "Introduction to Cybersecurity for Business",
      author: "Keny White",
      category: "Cryptocurrency",
      price: 19,
      image: "/images/course3.jpg",
      image2: "/images/course3Big.jpg",
      rating: 1.5,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      duration: "25 hours",
      skill_level: "Beginner",
      language: "English",
      instructorImg1: "/images/Instructor.jpeg",
      instructorImg2: "/images/Instructor2.jpeg",
      aka: "Professor",
      instructorInfo: "Lorem ipsum dolor sit amet. Qui incidunt dolores non similique ducimus et debitis molestiae. Et autem quia eum reprehenderit voluptates est reprehenderit illo est enim perferendis est neque sunt. Nam amet sunt aut vero mollitia ut ipsum corporis vel facere eius et quia aspernatur qui fugiat repudiandae. Et officiis inventore et quis enim ut quaerat corporis sed reprehenderit odit sit saepe distinctio et accusantium repellendus ea enim harum."
    },
    {
      name: "Online Master of Computer Science",
      slug: "Online Master of Computer Science",
      author: "Keny White",
      category: "Stock Trading",
      price: 28,
      image: "/images/course4.jpg",
      image2: "/images/course4Big.jpg",
      rating: 2,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      duration: "25 hours",
      skill_level: "Beginner",
      language: "English",
      instructorImg1: "/images/Instructor.jpeg",
      instructorImg2: "/images/Instructor2.jpeg",
      aka: "Professor",
      instructorInfo: "Lorem ipsum dolor sit amet. Qui incidunt dolores non similique ducimus et debitis molestiae. Et autem quia eum reprehenderit voluptates est reprehenderit illo est enim perferendis est neque sunt. Nam amet sunt aut vero mollitia ut ipsum corporis vel facere eius et quia aspernatur qui fugiat repudiandae. Et officiis inventore et quis enim ut quaerat corporis sed reprehenderit odit sit saepe distinctio et accusantium repellendus ea enim harum."
    },
    {
      name: "Supply Chain Excellence",
      slug: "Supply Chain Excellence",
      author: "Keny White",
      category: "Digital Marketing",
      price: 5,
      image: "/images/course5.jpg",
      image2: "/images/course5Big.jpg",
      rating: 2.5,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      duration: "25 hours",
      skill_level: "Beginner",
      language: "English",
      instructorImg1: "/images/Instructor.jpeg",
      instructorImg2: "/images/Instructor2.jpeg",
      aka: "Professor",
      instructorInfo: "Lorem ipsum dolor sit amet. Qui incidunt dolores non similique ducimus et debitis molestiae. Et autem quia eum reprehenderit voluptates est reprehenderit illo est enim perferendis est neque sunt. Nam amet sunt aut vero mollitia ut ipsum corporis vel facere eius et quia aspernatur qui fugiat repudiandae. Et officiis inventore et quis enim ut quaerat corporis sed reprehenderit odit sit saepe distinctio et accusantium repellendus ea enim harum."
    },
    {
      name: "Applied Cryptography Specialization",
      slug: "Applied Cryptography Specialization",
      author: "Keny White",
      category: "Forex",
      price: 22,
      image: "/images/course6.jpg",
      image2: "/images/course6Big.jpg",
      rating: 3.0,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      duration: "25 hours",
      skill_level: "Beginner",
      language: "English",
      instructorImg1: "/images/Instructor.jpeg",
      instructorImg2: "/images/Instructor2.jpeg",
      aka: "Professor",
      instructorInfo: "Lorem ipsum dolor sit amet. Qui incidunt dolores non similique ducimus et debitis molestiae. Et autem quia eum reprehenderit voluptates est reprehenderit illo est enim perferendis est neque sunt. Nam amet sunt aut vero mollitia ut ipsum corporis vel facere eius et quia aspernatur qui fugiat repudiandae. Et officiis inventore et quis enim ut quaerat corporis sed reprehenderit odit sit saepe distinctio et accusantium repellendus ea enim harum."
    },
    {
      name: "Introduction to Blockchain Specialization",
      slug: "Introduction to Blockchain Specialization",
      author: "Keny White",
      category: "Cryptocurrency",
      price: 9,
      image: "/images/course7.jpg",
      image2: "/images/course7Big.jpg",
      rating: 3.5,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      duration: "25 hours",
      skill_level: "Beginner",
      language: "English",
      instructorImg1: "/images/Instructor.jpeg",
      instructorImg2: "/images/Instructor2.jpeg",
      aka: "Professor",
      instructorInfo: "Lorem ipsum dolor sit amet. Qui incidunt dolores non similique ducimus et debitis molestiae. Et autem quia eum reprehenderit voluptates est reprehenderit illo est enim perferendis est neque sunt. Nam amet sunt aut vero mollitia ut ipsum corporis vel facere eius et quia aspernatur qui fugiat repudiandae. Et officiis inventore et quis enim ut quaerat corporis sed reprehenderit odit sit saepe distinctio et accusantium repellendus ea enim harum."
    },
    {
      name: "Reminiscences of a Stock Operator",
      slug: "Reminiscences of a Stock Operator",
      author: "Keny White",
      category: "Stock Trading",
      price: 5,
      image: "/images/course5.jpg",
      image2: "/images/course5Big.jpg",
      rating: 4.0,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      duration: "25 hours",
      skill_level: "Beginner",
      language: "English",
      instructorImg1: "/images/Instructor.jpeg",
      instructorImg2: "/images/Instructor2.jpeg",
      aka: "Professor",
      instructorInfo: "Lorem ipsum dolor sit amet. Qui incidunt dolores non similique ducimus et debitis molestiae. Et autem quia eum reprehenderit voluptates est reprehenderit illo est enim perferendis est neque sunt. Nam amet sunt aut vero mollitia ut ipsum corporis vel facere eius et quia aspernatur qui fugiat repudiandae. Et officiis inventore et quis enim ut quaerat corporis sed reprehenderit odit sit saepe distinctio et accusantium repellendus ea enim harum."
    },
    {
      name: "Transacting on the blockchain",
      slug: "Transacting on the blockchain",
      author: "Keny White",
      category: "Digital Marketing",
      price: 45,
      image: "/images/course8.jpg",
      image2: "/images/course8Big.jpg",
      rating: 4.5,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      duration: "25 hours",
      skill_level: "Beginner",
      language: "English",
      instructorImg1: "/images/Instructor.jpeg",
      instructorImg2: "/images/Instructor2.jpeg",
      aka: "Professor",
      instructorInfo: "Lorem ipsum dolor sit amet. Qui incidunt dolores non similique ducimus et debitis molestiae. Et autem quia eum reprehenderit voluptates est reprehenderit illo est enim perferendis est neque sunt. Nam amet sunt aut vero mollitia ut ipsum corporis vel facere eius et quia aspernatur qui fugiat repudiandae. Et officiis inventore et quis enim ut quaerat corporis sed reprehenderit odit sit saepe distinctio et accusantium repellendus ea enim harum."
    },
    {
      name: "Currency Trading For Dummies",
      slug: "Currency Trading For Dummies",
      author: "Keny White",
      category: "Forex",
      price: 45,
      image: "/images/course8.jpg",
      image2: "/images/course8Big.jpg",
      rating: 5.0,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      duration: "25 hours",
      skill_level: "Beginner",
      language: "English",
      instructorImg1: "/images/Instructor.jpeg",
      instructorImg2: "/images/Instructor2.jpeg",
      aka: "Professor",
      instructorInfo: "Lorem ipsum dolor sit amet. Qui incidunt dolores non similique ducimus et debitis molestiae. Et autem quia eum reprehenderit voluptates est reprehenderit illo est enim perferendis est neque sunt. Nam amet sunt aut vero mollitia ut ipsum corporis vel facere eius et quia aspernatur qui fugiat repudiandae. Et officiis inventore et quis enim ut quaerat corporis sed reprehenderit odit sit saepe distinctio et accusantium repellendus ea enim harum."
    },
    {
      name: "The Crypto Trader",
      slug: "The Crypto Trader",
      author: "Keny White",
      category: "Cryptocurrency",
      price: 20,
      image: "/images/course2.jpg",
      image2: "/images/course2Big.jpg",
      rating: 4.5,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      duration: "25 hours",
      skill_level: "Beginner",
      language: "English",
      instructorImg1: "/images/instructor.jpeg",
      instructorImg2: "/images/instructor2.jpeg",
      aka: "Professor",
      instructorInfo: "Lorem ipsum dolor sit amet. Qui incidunt dolores non similique ducimus et debitis molestiae. Et autem quia eum reprehenderit voluptates est reprehenderit illo est enim perferendis est neque sunt. Nam amet sunt aut vero mollitia ut ipsum corporis vel facere eius et quia aspernatur qui fugiat repudiandae. Et officiis inventore et quis enim ut quaerat corporis sed reprehenderit odit sit saepe distinctio et accusantium repellendus ea enim harum."
    },
    {
      name: "Principles of Professional Speculation",
      slug: "Principles of Professional Speculation",
      author: "Keny White",
      category: "Stock Trading",
      price: 19,
      image: "/images/course3.jpg",
      image2: "/images/course3Big.jpg",
      rating: 4.0,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      duration: "25 hours",
      skill_level: "Beginner",
      language: "English",
      instructorImg1: "/images/Instructor.jpeg",
      instructorImg2: "/images/Instructor2.jpeg",
      aka: "Professor",
      instructorInfo: "Lorem ipsum dolor sit amet. Qui incidunt dolores non similique ducimus et debitis molestiae. Et autem quia eum reprehenderit voluptates est reprehenderit illo est enim perferendis est neque sunt. Nam amet sunt aut vero mollitia ut ipsum corporis vel facere eius et quia aspernatur qui fugiat repudiandae. Et officiis inventore et quis enim ut quaerat corporis sed reprehenderit odit sit saepe distinctio et accusantium repellendus ea enim harum."
    },
    {
      name: "Digital and Social Media Marketing",
      slug: "Digital and Social Media Marketing",
      author: "Keny White",
      category: "Digital Marketing",
      price: 22,
      image: "/images/course6.jpg",
      image2: "/images/course6Big.jpg",
      rating: 3.5,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      duration: "25 hours",
      skill_level: "Beginner",
      language: "English",
      instructorImg1: "/images/Instructor.jpeg",
      instructorImg2: "/images/Instructor2.jpeg",
      aka: "Professor",
      instructorInfo: "Lorem ipsum dolor sit amet. Qui incidunt dolores non similique ducimus et debitis molestiae. Et autem quia eum reprehenderit voluptates est reprehenderit illo est enim perferendis est neque sunt. Nam amet sunt aut vero mollitia ut ipsum corporis vel facere eius et quia aspernatur qui fugiat repudiandae. Et officiis inventore et quis enim ut quaerat corporis sed reprehenderit odit sit saepe distinctio et accusantium repellendus ea enim harum."
    },
    {
      name: "Forex Patterns and Probabilities",
      slug: "Forex Patterns and Probabilities",
      author: "Keny White",
      category: "Forex",
      price: 28,
      image: "/images/course4.jpg",
      image2: "/images/course4Big.jpg",
      rating: 3.0,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      duration: "25 hours",
      skill_level: "Beginner",
      language: "English",
      instructorImg1: "/images/Instructor.jpeg",
      instructorImg2: "/images/Instructor2.jpeg",
      aka: "Professor",
      instructorInfo: "Lorem ipsum dolor sit amet. Qui incidunt dolores non similique ducimus et debitis molestiae. Et autem quia eum reprehenderit voluptates est reprehenderit illo est enim perferendis est neque sunt. Nam amet sunt aut vero mollitia ut ipsum corporis vel facere eius et quia aspernatur qui fugiat repudiandae. Et officiis inventore et quis enim ut quaerat corporis sed reprehenderit odit sit saepe distinctio et accusantium repellendus ea enim harum."
    },
    {
      name: "Basics of Bitcoins and Blockchain",
      slug: "Basics of Bitcoins and Blockchain",
      author: "Keny White",
      category: "Cryptocurrency",
      price: 22,
      image: "/images/course6.jpg",
      image2: "/images/course6Big.jpg",
      rating: 3.5,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      duration: "25 hours",
      skill_level: "Beginner",
      language: "English",
      instructorImg1: "/images/Instructor.jpeg",
      instructorImg2: "/images/Instructor2.jpeg",
      aka: "Professor",
      instructorInfo: "Lorem ipsum dolor sit amet. Qui incidunt dolores non similique ducimus et debitis molestiae. Et autem quia eum reprehenderit voluptates est reprehenderit illo est enim perferendis est neque sunt. Nam amet sunt aut vero mollitia ut ipsum corporis vel facere eius et quia aspernatur qui fugiat repudiandae. Et officiis inventore et quis enim ut quaerat corporis sed reprehenderit odit sit saepe distinctio et accusantium repellendus ea enim harum."
    },
    {
      name: "Learn to Trade Momentum Stocks",
      slug: "Learn to Trade Momentum Stocks",
      author: "Keny White",
      category: "Stock Trading",
      price: 9,
      image: "/images/course7.jpg",
      image2: "/images/course7Big.jpg",
      rating: 4.0,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      duration: "25 hours",
      skill_level: "Beginner",
      language: "English",
      instructorImg1: "/images/Instructor.jpeg",
      instructorImg2: "/images/Instructor2.jpeg",
      aka: "Professor",
      instructorInfo: "Lorem ipsum dolor sit amet. Qui incidunt dolores non similique ducimus et debitis molestiae. Et autem quia eum reprehenderit voluptates est reprehenderit illo est enim perferendis est neque sunt. Nam amet sunt aut vero mollitia ut ipsum corporis vel facere eius et quia aspernatur qui fugiat repudiandae. Et officiis inventore et quis enim ut quaerat corporis sed reprehenderit odit sit saepe distinctio et accusantium repellendus ea enim harum."
    },
    {
      name: "E-Commerce Marketing and Management",
      slug: "E-Commerce Marketing and Management",
      author: "Keny White",
      category: "Digital Marketing",
      price: 5,
      image: "/images/course5.jpg",
      image2: "/images/course5Big.jpg",
      rating: 4.5,
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      duration: "25 hours",
      skill_level: "Beginner",
      language: "English",
      instructorImg1: "/images/Instructor.jpeg",
      instructorImg2: "/images/Instructor2.jpeg",
      aka: "Professor",
      instructorInfo: "Lorem ipsum dolor sit amet. Qui incidunt dolores non similique ducimus et debitis molestiae. Et autem quia eum reprehenderit voluptates est reprehenderit illo est enim perferendis est neque sunt. Nam amet sunt aut vero mollitia ut ipsum corporis vel facere eius et quia aspernatur qui fugiat repudiandae. Et officiis inventore et quis enim ut quaerat corporis sed reprehenderit odit sit saepe distinctio et accusantium repellendus ea enim harum."
    },
  ],
};

export default data;
